// SZRcStrings.h -- GENERATED by Mac/scripts/make-rc-strings.py from
// CPP/7zip/UI/FileManager/resource.rc and CPP/7zip/UI/GUI/resource.rc. Do not edit.
// The English text 7zFM / 7zG show with no language file, by lang ID, both sorted.
// kSZRcStrings: STRINGTABLE entries, else a dialog text all dialogs agree on.
// kSZRcDialogStrings: every dialog caption (dialog == id) and control text per dialog.
static const SZRcString kSZRcStrings[] =
{
  { 93, L"7-Zip: Browse Temp Files" },  // FileManager DIALOG 93 CAPTION
  { 94, L"Edit" },  // FileManager DIALOG 94 CAPTION
  { 95, L"7-Zip: Browse" },  // FileManager DIALOG 95 CAPTION
  { 96, L"Copy" },  // FileManager DIALOG 96 CAPTION
  { 97, L"Progress" },  // FileManager DIALOG 97 CAPTION
  { 98, L"Combo" },  // FileManager DIALOG 98 CAPTION
  { 99, L"ListView" },  // FileManager DIALOG 99 CAPTION
  { 408, L"&Close" },  // FileManager STRINGTABLE
  { 411, L"&Continue" },  // FileManager STRINGTABLE
  { 440, L"Yes to &All" },  // FileManager DIALOG 3500 PUSHBUTTON
  { 441, L"No to A&ll" },  // FileManager DIALOG 3500 PUSHBUTTON
  { 442, L"&Stop" },  // GUI DIALOG 7600 PUSHBUTTON
  { 443, L"&Restart" },  // GUI DIALOG 7600 PUSHBUTTON
  { 444, L"&Background" },  // FileManager DIALOG 97 DEFPUSHBUTTON
  { 445, L"&Foreground" },  // FileManager STRINGTABLE
  { 446, L"&Pause" },  // FileManager DIALOG 97 PUSHBUTTON
  { 447, L"Paused" },  // FileManager STRINGTABLE
  { 448, L"Are you sure you want to cancel?" },  // FileManager STRINGTABLE
  { 543, L"&View:" },  // FileManager DIALOG 2103 LTEXT
  { 737, L"Refresh" },  // FileManager DIALOG 93 PUSHBUTTON
  { 801, L"Bookmark" },  // FileManager STRINGTABLE
  { 1003, L"Path" },  // FileManager STRINGTABLE
  { 1004, L"Name" },  // FileManager STRINGTABLE
  { 1005, L"Extension" },  // FileManager STRINGTABLE
  { 1006, L"Folder" },  // FileManager STRINGTABLE
  { 1007, L"Size" },  // FileManager STRINGTABLE
  { 1008, L"Packed Size" },  // FileManager STRINGTABLE
  { 1009, L"Attributes" },  // FileManager STRINGTABLE
  { 1010, L"Created" },  // FileManager STRINGTABLE
  { 1011, L"Accessed" },  // FileManager STRINGTABLE
  { 1012, L"Modified" },  // FileManager STRINGTABLE
  { 1013, L"Solid" },  // FileManager STRINGTABLE
  { 1014, L"Commented" },  // FileManager STRINGTABLE
  { 1015, L"Encrypted" },  // FileManager STRINGTABLE
  { 1016, L"Split Before" },  // FileManager STRINGTABLE
  { 1017, L"Split After" },  // FileManager STRINGTABLE
  { 1018, L"Dictionary" },  // FileManager STRINGTABLE
  { 1019, L"CRC" },  // FileManager STRINGTABLE
  { 1020, L"Type" },  // FileManager STRINGTABLE
  { 1021, L"Anti" },  // FileManager STRINGTABLE
  { 1022, L"Method" },  // FileManager STRINGTABLE
  { 1023, L"Host OS" },  // FileManager STRINGTABLE
  { 1024, L"File System" },  // FileManager STRINGTABLE
  { 1025, L"User" },  // FileManager STRINGTABLE
  { 1026, L"Group" },  // FileManager STRINGTABLE
  { 1027, L"Block" },  // FileManager STRINGTABLE
  { 1028, L"Comment" },  // FileManager STRINGTABLE
  { 1029, L"Position" },  // FileManager STRINGTABLE
  { 1030, L"Path Prefix" },  // FileManager STRINGTABLE
  { 1031, L"Folders" },  // FileManager STRINGTABLE
  { 1032, L"Files" },  // FileManager STRINGTABLE
  { 1033, L"Version" },  // FileManager STRINGTABLE
  { 1034, L"Volume" },  // FileManager STRINGTABLE
  { 1035, L"Multivolume" },  // FileManager STRINGTABLE
  { 1036, L"Offset" },  // FileManager STRINGTABLE
  { 1037, L"Links" },  // FileManager STRINGTABLE
  { 1038, L"Blocks" },  // FileManager STRINGTABLE
  { 1039, L"Volumes" },  // FileManager STRINGTABLE
  { 1041, L"64-bit" },  // FileManager STRINGTABLE
  { 1042, L"Big-endian" },  // FileManager STRINGTABLE
  { 1043, L"CPU" },  // FileManager STRINGTABLE
  { 1044, L"Physical Size" },  // FileManager STRINGTABLE
  { 1045, L"Headers Size" },  // FileManager STRINGTABLE
  { 1046, L"Checksum" },  // FileManager STRINGTABLE
  { 1047, L"Characteristics" },  // FileManager STRINGTABLE
  { 1048, L"Virtual Address" },  // FileManager STRINGTABLE
  { 1049, L"ID" },  // FileManager STRINGTABLE
  { 1050, L"Short Name" },  // FileManager STRINGTABLE
  { 1051, L"Creator Application" },  // FileManager STRINGTABLE
  { 1052, L"Sector Size" },  // FileManager STRINGTABLE
  { 1053, L"Mode" },  // FileManager STRINGTABLE
  { 1054, L"Symbolic Link" },  // FileManager STRINGTABLE
  { 1055, L"Error" },  // FileManager STRINGTABLE
  { 1056, L"Total Size" },  // FileManager STRINGTABLE
  { 1057, L"Free Space" },  // FileManager STRINGTABLE
  { 1058, L"Cluster Size" },  // FileManager STRINGTABLE
  { 1059, L"Label" },  // FileManager STRINGTABLE
  { 1060, L"Local Name" },  // FileManager STRINGTABLE
  { 1061, L"Provider" },  // FileManager STRINGTABLE
  { 1062, L"NT Security" },  // FileManager STRINGTABLE
  { 1063, L"Alternate Stream" },  // FileManager STRINGTABLE
  { 1064, L"Aux" },  // FileManager STRINGTABLE
  { 1065, L"Deleted" },  // FileManager STRINGTABLE
  { 1066, L"Is Tree" },  // FileManager STRINGTABLE
  { 1067, L"SHA-1" },  // FileManager STRINGTABLE
  { 1068, L"SHA-256" },  // FileManager STRINGTABLE
  { 1069, L"Error Type" },  // FileManager STRINGTABLE
  { 1070, L"Errors" },  // FileManager STRINGTABLE
  { 1071, L"Errors" },  // FileManager STRINGTABLE
  { 1072, L"Warnings" },  // FileManager STRINGTABLE
  { 1073, L"Warning" },  // FileManager STRINGTABLE
  { 1074, L"Streams" },  // FileManager STRINGTABLE
  { 1075, L"Alternate Streams" },  // FileManager STRINGTABLE
  { 1076, L"Alternate Streams Size" },  // FileManager STRINGTABLE
  { 1077, L"Virtual Size" },  // FileManager STRINGTABLE
  { 1078, L"Unpack Size" },  // FileManager STRINGTABLE
  { 1079, L"Total Physical Size" },  // FileManager STRINGTABLE
  { 1080, L"Volume Index" },  // FileManager STRINGTABLE
  { 1081, L"SubType" },  // FileManager STRINGTABLE
  { 1082, L"Short Comment" },  // FileManager STRINGTABLE
  { 1083, L"Code Page" },  // FileManager STRINGTABLE
  { 1084, L"Is not archive type" },  // FileManager STRINGTABLE
  { 1085, L"Physical Size can't be detected" },  // FileManager STRINGTABLE
  { 1086, L"Zeros Tail Is Allowed" },  // FileManager STRINGTABLE
  { 1087, L"Tail Size" },  // FileManager STRINGTABLE
  { 1088, L"Embedded Stub Size" },  // FileManager STRINGTABLE
  { 1089, L"Link" },  // FileManager STRINGTABLE
  { 1090, L"Hard Link" },  // FileManager STRINGTABLE
  { 1091, L"iNode" },  // FileManager STRINGTABLE
  { 1092, L"Stream ID" },  // FileManager STRINGTABLE
  { 1093, L"Read-only" },  // FileManager STRINGTABLE
  { 1094, L"Out Name" },  // FileManager STRINGTABLE
  { 1095, L"Copy Link" },  // FileManager STRINGTABLE
  { 1096, L"ArcFileName" },  // FileManager STRINGTABLE
  { 1097, L"IsHash" },  // FileManager STRINGTABLE
  { 1098, L"Metadata Changed" },  // FileManager STRINGTABLE
  { 1099, L"User ID" },  // FileManager STRINGTABLE
  { 1100, L"Group ID" },  // FileManager STRINGTABLE
  { 1101, L"Device Major" },  // FileManager STRINGTABLE
  { 1102, L"Device Minor" },  // FileManager STRINGTABLE
  { 1103, L"Dev Major" },  // FileManager STRINGTABLE
  { 1104, L"Dev Minor" },  // FileManager STRINGTABLE
  { 2100, L"Options" },  // FileManager STRINGTABLE
  { 2101, L"Language" },  // FileManager DIALOG 2101 CAPTION
  { 2102, L"Language:" },  // FileManager DIALOG 2101 LTEXT
  { 2103, L"Editor" },  // FileManager DIALOG 2103 CAPTION
  { 2104, L"&Editor:" },  // FileManager DIALOG 2103 LTEXT
  { 2105, L"&Diff:" },  // FileManager DIALOG 2103 LTEXT
  { 2200, L"System" },  // FileManager DIALOG 2200 CAPTION
  { 2201, L"Associate 7-Zip with:" },  // FileManager DIALOG 2200 LTEXT
  { 2202, L"All users" },  // FileManager STRINGTABLE
  { 2300, L"7-Zip" },  // FileManager DIALOG 2300 CAPTION
  { 2301, L"Integrate 7-Zip to shell context menu" },  // FileManager DIALOG 2300 CONTROL
  { 2302, L"Cascaded context menu" },  // FileManager DIALOG 2300 CONTROL
  { 2303, L"Context menu items:" },  // FileManager DIALOG 2300 LTEXT
  { 2304, L"Icons in context menu" },  // FileManager DIALOG 2300 CONTROL
  { 2310, L"(32-bit)" },  // FileManager DIALOG 2300 CONTROL
  { 2320, L"<Folder>" },  // FileManager STRINGTABLE
  { 2321, L"<Archive>" },  // FileManager STRINGTABLE
  { 2322, L"Open archive" },  // FileManager STRINGTABLE
  { 2323, L"Extract files..." },  // FileManager STRINGTABLE
  { 2324, L"Add to archive..." },  // FileManager STRINGTABLE
  { 2325, L"Test archive" },  // FileManager STRINGTABLE
  { 2326, L"Extract Here" },  // FileManager STRINGTABLE
  { 2327, L"Extract to {0}" },  // FileManager STRINGTABLE
  { 2328, L"Add to {0}" },  // FileManager STRINGTABLE
  { 2329, L"Compress and email..." },  // FileManager STRINGTABLE
  { 2330, L"Compress to {0} and email" },  // FileManager STRINGTABLE
  { 2400, L"Folders" },  // FileManager DIALOG 2400 CAPTION
  { 2401, L"&Working folder" },  // FileManager DIALOG 2400 LTEXT
  { 2402, L"&System temp folder" },  // FileManager DIALOG 2400 CONTROL
  { 2403, L"&Current" },  // FileManager DIALOG 2400 CONTROL
  { 2404, L"Specified:" },  // FileManager DIALOG 2400 CONTROL
  { 2405, L"Use for removable drives only" },  // FileManager DIALOG 2400 CONTROL
  { 2406, L"Specify a location for temporary archive files." },  // FileManager STRINGTABLE
  { 2500, L"Settings" },  // FileManager DIALOG 2500 CAPTION
  { 2501, L"Show \"..\" item" },  // FileManager DIALOG 2500 CONTROL
  { 2502, L"Show real file &icons" },  // FileManager DIALOG 2500 CONTROL
  { 2503, L"Show system &menu" },  // FileManager DIALOG 2500 CONTROL
  { 2504, L"&Full row select" },  // FileManager DIALOG 2500 CONTROL
  { 2505, L"Show &grid lines" },  // FileManager DIALOG 2500 CONTROL
  { 2506, L"&Single-click to open an item" },  // FileManager DIALOG 2500 CONTROL
  { 2507, L"&Alternative selection mode" },  // FileManager DIALOG 2500 CONTROL
  { 2508, L"Use &large memory pages" },  // FileManager DIALOG 2500 CONTROL
  { 2900, L"About 7-Zip" },  // FileManager DIALOG 2900 CAPTION
  { 2901, L"7-Zip is free software" },  // FileManager DIALOG 2900 LTEXT
  { 3000, L"The system cannot allocate the required amount of memory" },  // FileManager STRINGTABLE
  { 3001, L"There are no errors" },  // FileManager STRINGTABLE
  { 3002, L"{0} object(s) selected" },  // FileManager STRINGTABLE
  { 3003, L"Cannot create folder '{0}'" },  // FileManager STRINGTABLE
  { 3004, L"Update operations are not supported for this archive." },  // FileManager STRINGTABLE
  { 3005, L"Cannot open file '{0}' as archive" },  // FileManager STRINGTABLE
  { 3006, L"Cannot open encrypted archive '{0}'. Wrong password?" },  // FileManager STRINGTABLE
  { 3007, L"Unsupported archive type" },  // FileManager STRINGTABLE
  { 3008, L"File {0} is already exist" },  // FileManager STRINGTABLE
  { 3009, L"File '{0}' was modified.\nDo you want to update it in the archive?" },  // FileManager STRINGTABLE
  { 3010, L"Cannot update file\n'{0}'" },  // FileManager STRINGTABLE
  { 3011, L"Cannot start editor." },  // FileManager STRINGTABLE
  { 3012, L"The file looks like a virus (the file name contains long spaces in name)." },  // FileManager STRINGTABLE
  { 3013, L"The operation cannot be called from a folder that has a long path." },  // FileManager STRINGTABLE
  { 3014, L"You must select one file" },  // FileManager STRINGTABLE
  { 3015, L"You must select one or more files" },  // FileManager STRINGTABLE
  { 3016, L"Too many items" },  // FileManager STRINGTABLE
  { 3017, L"Cannot open the file as {0} archive" },  // FileManager STRINGTABLE
  { 3018, L"The file is open as {0} archive" },  // FileManager STRINGTABLE
  { 3019, L"The archive is open with offset" },  // FileManager STRINGTABLE
  { 3300, L"Extracting" },  // FileManager STRINGTABLE
  { 3301, L"Compressing" },  // GUI STRINGTABLE
  { 3302, L"Testing" },  // FileManager STRINGTABLE
  { 3303, L"Opening..." },  // FileManager STRINGTABLE
  { 3304, L"Scanning..." },  // FileManager STRINGTABLE
  { 3305, L"Removing" },  // FileManager STRINGTABLE
  { 3320, L"Adding" },  // FileManager STRINGTABLE
  { 3321, L"Updating" },  // FileManager STRINGTABLE
  { 3322, L"Analyzing" },  // FileManager STRINGTABLE
  { 3323, L"Replicating" },  // FileManager STRINGTABLE
  { 3324, L"Repacking" },  // FileManager STRINGTABLE
  { 3325, L"Skipping" },  // FileManager STRINGTABLE
  { 3326, L"Deleting" },  // FileManager STRINGTABLE
  { 3327, L"Header creating" },  // FileManager STRINGTABLE
  { 3400, L"Extract" },  // GUI DIALOG 3400 CAPTION
  { 3401, L"E&xtract to:" },  // GUI DIALOG 3400 LTEXT
  { 3402, L"Specify a location for extracted files." },  // FileManager STRINGTABLE
  { 3410, L"Path mode:" },  // GUI DIALOG 3400 LTEXT
  { 3411, L"Full pathnames" },  // FileManager STRINGTABLE
  { 3412, L"No pathnames" },  // FileManager STRINGTABLE
  { 3413, L"Absolute pathnames" },  // FileManager STRINGTABLE
  { 3414, L"Relative pathnames" },  // FileManager STRINGTABLE
  { 3420, L"Overwrite mode:" },  // GUI DIALOG 3400 LTEXT
  { 3421, L"Ask before overwrite" },  // FileManager STRINGTABLE
  { 3422, L"Overwrite without prompt" },  // FileManager STRINGTABLE
  { 3423, L"Skip existing files" },  // FileManager STRINGTABLE
  { 3424, L"Auto rename" },  // FileManager STRINGTABLE
  { 3425, L"Auto rename existing files" },  // FileManager STRINGTABLE
  { 3430, L"Eliminate duplication of root folder" },  // FileManager DIALOG 2300 CONTROL
  { 3431, L"Restore file security" },  // GUI DIALOG 3400 CONTROL
  { 3440, L"Propagate Zone.Id stream:" },  // FileManager DIALOG 2300 LTEXT
  { 3441, L"For Office files" },  // FileManager STRINGTABLE
  { 3500, L"Confirm File Replace" },  // FileManager DIALOG 3500 CAPTION
  { 3501, L"Destination folder already contains processed file." },  // FileManager DIALOG 3500 LTEXT
  { 3502, L"Would you like to replace the existing file" },  // FileManager DIALOG 3500 LTEXT
  { 3503, L"with this one?" },  // FileManager DIALOG 3500 LTEXT
  { 3504, L"{0} bytes" },  // FileManager STRINGTABLE
  { 3505, L"A&uto Rename" },  // FileManager DIALOG 3500 PUSHBUTTON
  { 3700, L"Unsupported compression method for '{0}'." },  // FileManager STRINGTABLE
  { 3701, L"Data error in '{0}'. File is broken" },  // FileManager STRINGTABLE
  { 3702, L"CRC failed in '{0}'. File is broken." },  // FileManager STRINGTABLE
  { 3703, L"Data error in encrypted file '{0}'. Wrong password?" },  // FileManager STRINGTABLE
  { 3704, L"CRC failed in encrypted file '{0}'. Wrong password?" },  // FileManager STRINGTABLE
  { 3710, L"Wrong password?" },  // FileManager STRINGTABLE
  { 3721, L"Unsupported compression method" },  // FileManager STRINGTABLE
  { 3722, L"Data error" },  // FileManager STRINGTABLE
  { 3723, L"CRC failed" },  // FileManager STRINGTABLE
  { 3724, L"Unavailable data" },  // FileManager STRINGTABLE
  { 3725, L"Unexpected end of data" },  // FileManager STRINGTABLE
  { 3726, L"There are some data after the end of the payload data" },  // FileManager STRINGTABLE
  { 3727, L"Is not archive" },  // FileManager STRINGTABLE
  { 3728, L"Headers Error" },  // FileManager STRINGTABLE
  { 3729, L"Wrong password" },  // FileManager STRINGTABLE
  { 3763, L"Unavailable start of archive" },  // FileManager STRINGTABLE
  { 3764, L"Unconfirmed start of archive" },  // FileManager STRINGTABLE
  { 3768, L"Unsupported feature" },  // FileManager STRINGTABLE
  { 3800, L"Enter password" },  // FileManager DIALOG 3800 CAPTION
  { 3802, L"Reenter password:" },  // GUI DIALOG 4000 LTEXT
  { 3804, L"Passwords do not match" },  // GUI STRINGTABLE
  { 3805, L"Use only English letters, numbers and special characters (!, #, $, ...) for password." },  // GUI STRINGTABLE
  { 3806, L"Password is too long" },  // GUI STRINGTABLE
  { 3807, L"Password" },  // GUI DIALOG 3400 GROUPBOX
  { 3900, L"Elapsed time:" },  // FileManager DIALOG 97 LTEXT
  { 3901, L"Remaining time:" },  // FileManager DIALOG 97 LTEXT
  { 3902, L"Total size:" },  // FileManager DIALOG 97 LTEXT
  { 3904, L"Processed:" },  // FileManager DIALOG 97 LTEXT
  { 3905, L"Compression ratio:" },  // FileManager DIALOG 97 LTEXT
  { 3906, L"Errors:" },  // FileManager DIALOG 97 LTEXT
  { 3907, L"Archives:" },  // GUI STRINGTABLE
  { 4000, L"Add to Archive" },  // GUI DIALOG 4000 CAPTION
  { 4001, L"&Archive:" },  // GUI DIALOG 4000 LTEXT
  { 4002, L"&Update mode:" },  // GUI DIALOG 4000 LTEXT
  { 4003, L"Archive &format:" },  // GUI DIALOG 4000 LTEXT
  { 4004, L"Compression &level:" },  // GUI DIALOG 4000 LTEXT
  { 4005, L"Compression &method:" },  // GUI DIALOG 4000 LTEXT
  { 4006, L"&Dictionary size:" },  // GUI DIALOG 4000 LTEXT
  { 4007, L"&Word size:" },  // GUI DIALOG 4000 LTEXT
  { 4008, L"&Solid Block size:" },  // GUI DIALOG 4000 LTEXT
  { 4010, L"Parameters:" },  // GUI DIALOG 4000 LTEXT
  { 4011, L"Options" },  // GUI DIALOG 4000 GROUPBOX
  { 4012, L"Create SF&X archive" },  // GUI DIALOG 4000 CONTROL
  { 4013, L"Compress shared files" },  // GUI DIALOG 4000 CONTROL
  { 4014, L"Encryption" },  // GUI DIALOG 4000 GROUPBOX
  { 4015, L"&Encryption method:" },  // GUI DIALOG 4000 LTEXT
  { 4016, L"Encrypt file &names" },  // GUI DIALOG 4000 CONTROL
  { 4017, L"Memory usage for Compressing:" },  // GUI DIALOG 4000 LTEXT
  { 4018, L"Memory usage for Decompressing:" },  // GUI DIALOG 4000 LTEXT
  { 4019, L"Delete files after compression" },  // GUI DIALOG 4000 CONTROL
  { 4040, L"Store symbolic links" },  // GUI DIALOG 14001 CONTROL
  { 4041, L"Store hard links" },  // GUI DIALOG 14001 CONTROL
  { 4042, L"Store alternate data streams" },  // GUI DIALOG 14001 CONTROL
  { 4043, L"Store file security" },  // GUI DIALOG 14001 CONTROL
  { 4050, L"Store" },  // GUI STRINGTABLE
  { 4051, L"Fastest" },  // GUI STRINGTABLE
  { 4052, L"Fast" },  // GUI STRINGTABLE
  { 4053, L"Normal" },  // GUI STRINGTABLE
  { 4054, L"Maximum" },  // GUI STRINGTABLE
  { 4055, L"Ultra" },  // GUI STRINGTABLE
  { 4060, L"Add and replace files" },  // GUI STRINGTABLE
  { 4061, L"Update and add files" },  // GUI STRINGTABLE
  { 4062, L"Freshen existing files" },  // GUI STRINGTABLE
  { 4063, L"Synchronize files" },  // GUI STRINGTABLE
  { 4070, L"Browse" },  // GUI STRINGTABLE
  { 4071, L"All Files" },  // GUI STRINGTABLE
  { 4072, L"Non-solid" },  // GUI STRINGTABLE
  { 4073, L"Solid" },  // GUI STRINGTABLE
  { 4080, L"Time" },  // GUI DIALOG 14001 GROUPBOX
  { 4081, L"Timestamp precision:" },  // GUI DIALOG 14001 LTEXT
  { 4082, L"Store modification time" },  // GUI DIALOG 14001 CONTROL
  { 4083, L"Store creation time" },  // GUI DIALOG 14001 CONTROL
  { 4084, L"Store last access time" },  // GUI DIALOG 14001 CONTROL
  { 4085, L"Set archive time to latest file time" },  // GUI DIALOG 14001 CONTROL
  { 4086, L"Do not change source files last access time" },  // GUI DIALOG 14001 CONTROL
  { 4090, L"sec" },  // GUI STRINGTABLE
  { 4091, L"ns" },  // GUI STRINGTABLE
  { 6000, L"Copy" },  // FileManager STRINGTABLE
  { 6001, L"Move" },  // FileManager STRINGTABLE
  { 6002, L"Copy to:" },  // FileManager STRINGTABLE
  { 6003, L"Move to:" },  // FileManager STRINGTABLE
  { 6004, L"Copying..." },  // FileManager STRINGTABLE
  { 6005, L"Moving..." },  // FileManager STRINGTABLE
  { 6006, L"Renaming..." },  // FileManager STRINGTABLE
  { 6008, L"Operation is not supported." },  // FileManager STRINGTABLE
  { 6009, L"Error Renaming File or Folder" },  // FileManager STRINGTABLE
  { 6010, L"Confirm File Copy" },  // FileManager STRINGTABLE
  { 6011, L"Are you sure you want to copy files to archive" },  // FileManager STRINGTABLE
  { 6100, L"Confirm File Delete" },  // FileManager STRINGTABLE
  { 6101, L"Confirm Folder Delete" },  // FileManager STRINGTABLE
  { 6102, L"Confirm Multiple File Delete" },  // FileManager STRINGTABLE
  { 6103, L"Are you sure you want to delete '{0}'?" },  // FileManager STRINGTABLE
  { 6104, L"Are you sure you want to delete the folder '{0}' and all its contents?" },  // FileManager STRINGTABLE
  { 6105, L"Are you sure you want to delete these {0} items?" },  // FileManager STRINGTABLE
  { 6106, L"Deleting..." },  // FileManager STRINGTABLE
  { 6107, L"Error Deleting File or Folder" },  // FileManager STRINGTABLE
  { 6108, L"The system cannot move a file with long path to the Recycle Bin" },  // FileManager STRINGTABLE
  { 6300, L"Create Folder" },  // FileManager STRINGTABLE
  { 6301, L"Create File" },  // FileManager STRINGTABLE
  { 6302, L"Folder name:" },  // FileManager STRINGTABLE
  { 6303, L"File Name:" },  // FileManager STRINGTABLE
  { 6304, L"New Folder" },  // FileManager STRINGTABLE
  { 6305, L"New File" },  // FileManager STRINGTABLE
  { 6306, L"Error Creating Folder" },  // FileManager STRINGTABLE
  { 6307, L"Error Creating File" },  // FileManager STRINGTABLE
  { 6400, L"Comment" },  // FileManager STRINGTABLE
  { 6401, L"&Comment:" },  // FileManager STRINGTABLE
  { 6402, L"Select" },  // FileManager STRINGTABLE
  { 6403, L"Deselect" },  // FileManager STRINGTABLE
  { 6404, L"Mask:" },  // FileManager STRINGTABLE
  { 6600, L"Properties" },  // FileManager STRINGTABLE
  { 6601, L"Folders History" },  // FileManager STRINGTABLE
  { 6602, L"7-Zip: Diagnostic messages" },  // FileManager DIALOG 6602 CAPTION
  { 7100, L"Computer" },  // FileManager STRINGTABLE
  { 7101, L"Network" },  // FileManager STRINGTABLE
  { 7102, L"Documents" },  // FileManager STRINGTABLE
  { 7103, L"System" },  // FileManager STRINGTABLE
  { 7200, L"Add" },  // FileManager STRINGTABLE
  { 7201, L"Extract" },  // FileManager STRINGTABLE
  { 7202, L"Test" },  // FileManager STRINGTABLE
  { 7203, L"Copy" },  // FileManager STRINGTABLE
  { 7204, L"Move" },  // FileManager STRINGTABLE
  { 7205, L"Delete" },  // FileManager STRINGTABLE
  { 7206, L"Info" },  // FileManager STRINGTABLE
  { 7300, L"Split File" },  // FileManager DIALOG 7300 CAPTION
  { 7301, L"&Split to:" },  // FileManager DIALOG 7300 LTEXT
  { 7303, L"Splitting..." },  // FileManager STRINGTABLE
  { 7304, L"Confirm Splitting" },  // FileManager STRINGTABLE
  { 7305, L"Are you sure you want to split file into {0} volumes?" },  // FileManager STRINGTABLE
  { 7306, L"Volume size must be smaller than size of original file" },  // FileManager STRINGTABLE
  { 7307, L"Incorrect volume size" },  // FileManager STRINGTABLE
  { 7308, L"Specified volume size: {0} bytes.\nAre you sure you want to split archive into such volumes?" },  // GUI STRINGTABLE
  { 7400, L"Combine Files" },  // FileManager STRINGTABLE
  { 7401, L"&Combine to:" },  // FileManager STRINGTABLE
  { 7402, L"Combining..." },  // FileManager STRINGTABLE
  { 7403, L"Select only first part of split file" },  // FileManager STRINGTABLE
  { 7404, L"Cannot detect file as split file" },  // FileManager STRINGTABLE
  { 7405, L"Cannot find more than one part of split file" },  // FileManager STRINGTABLE
  { 7500, L"Checksum calculating..." },  // FileManager STRINGTABLE
  { 7501, L"Checksum information" },  // FileManager STRINGTABLE
  { 7502, L"CRC checksum for data:" },  // FileManager STRINGTABLE
  { 7503, L"CRC checksum for data and names:" },  // FileManager STRINGTABLE
  { 7504, L"CRC checksum for streams and names:" },  // FileManager STRINGTABLE
  { 7600, L"Benchmark" },  // GUI DIALOG 7600 CAPTION
  { 7601, L"Memory usage:" },  // GUI DIALOG 7600 LTEXT
  { 7602, L"Compressing" },  // GUI DIALOG 7600 GROUPBOX
  { 7603, L"Decompressing" },  // GUI DIALOG 7600 GROUPBOX
  { 7604, L"Rating" },  // GUI DIALOG 7600 RTEXT
  { 7605, L"Total Rating" },  // GUI DIALOG 7600 GROUPBOX
  { 7606, L"Current" },  // GUI DIALOG 7600 LTEXT
  { 7607, L"Resulting" },  // GUI DIALOG 7600 LTEXT
  { 7608, L"CPU Usage" },  // GUI DIALOG 7600 RTEXT
  { 7609, L"Rating / Usage" },  // GUI DIALOG 7600 RTEXT
  { 7610, L"Passes:" },  // GUI DIALOG 7600 LTEXT
  { 7699, L"Benchmark" },  // GUI DIALOG 7699 CAPTION
  { 7700, L"Link" },  // FileManager DIALOG 7700 CAPTION
  { 7701, L"Link" },  // FileManager DIALOG 7700 DEFPUSHBUTTON
  { 7702, L"Link from:" },  // FileManager DIALOG 7700 LTEXT
  { 7703, L"Link to:" },  // FileManager DIALOG 7700 LTEXT
  { 7710, L"Link Type" },  // FileManager DIALOG 7700 GROUPBOX
  { 7711, L"Hard Link" },  // FileManager DIALOG 7700 CONTROL
  { 7712, L"File Symbolic Link" },  // FileManager DIALOG 7700 CONTROL
  { 7713, L"Directory Symbolic Link" },  // FileManager DIALOG 7700 CONTROL
  { 7714, L"Directory Junction" },  // FileManager DIALOG 7700 CONTROL
  { 7715, L"WSL" },  // FileManager DIALOG 7700 CONTROL
  { 7800, L"Memory usage request" },  // FileManager DIALOG 7800 CAPTION
  { 7801, L"Change allowed limit for next operations" },  // FileManager DIALOG 7800 CONTROL
  { 7802, L"&Repeat selected action for current operation" },  // FileManager DIALOG 7800 CONTROL
  { 7803, L"Action" },  // FileManager DIALOG 7800 GROUPBOX
  { 7810, L"The operation was blocked by 7-Zip." },  // GUI STRINGTABLE
  { 7811, L"The operation requires big amount of memory (RAM)." },  // FileManager STRINGTABLE
  { 7812, L"required memory usage size" },  // FileManager STRINGTABLE
  { 7813, L"allowed memory usage limit" },  // FileManager STRINGTABLE
  { 7814, L"memory usage limit set by 7-Zip" },  // FileManager STRINGTABLE
  { 7815, L"RAM size" },  // FileManager STRINGTABLE
  { 7820, L"&Allow archive unpacking" },  // FileManager DIALOG 7800 CONTROL
  { 7821, L"&Skip archive unpacking" },  // FileManager DIALOG 7800 CONTROL
  { 7822, L"Archive extraction was skipped." },  // FileManager STRINGTABLE
  { 14001, L"Options" },  // GUI DIALOG 14001 CAPTION
};

static const SZRcDialogString kSZRcDialogStrings[] =
{
  { 93, 93, L"7-Zip: Browse Temp Files" },  // FileManager DIALOG 93 CAPTION
  { 93, 737, L"Refresh" },  // FileManager DIALOG 93 PUSHBUTTON
  { 93, 7205, L"Delete" },  // FileManager DIALOG 93 PUSHBUTTON
  { 94, 94, L"Edit" },  // FileManager DIALOG 94 CAPTION
  { 95, 95, L"7-Zip: Browse" },  // FileManager DIALOG 95 CAPTION
  { 96, 96, L"Copy" },  // FileManager DIALOG 96 CAPTION
  { 97, 97, L"Progress" },  // FileManager DIALOG 97 CAPTION
  { 97, 444, L"&Background" },  // FileManager DIALOG 97 DEFPUSHBUTTON
  { 97, 446, L"&Pause" },  // FileManager DIALOG 97 PUSHBUTTON
  { 97, 1008, L"Compressed size:" },  // FileManager DIALOG 97 LTEXT
  { 97, 1032, L"Files:" },  // FileManager DIALOG 97 LTEXT
  { 97, 3900, L"Elapsed time:" },  // FileManager DIALOG 97 LTEXT
  { 97, 3901, L"Remaining time:" },  // FileManager DIALOG 97 LTEXT
  { 97, 3902, L"Total size:" },  // FileManager DIALOG 97 LTEXT
  { 97, 3903, L"Speed:" },  // FileManager DIALOG 97 LTEXT
  { 97, 3904, L"Processed:" },  // FileManager DIALOG 97 LTEXT
  { 97, 3905, L"Compression ratio:" },  // FileManager DIALOG 97 LTEXT
  { 97, 3906, L"Errors:" },  // FileManager DIALOG 97 LTEXT
  { 98, 98, L"Combo" },  // FileManager DIALOG 98 CAPTION
  { 99, 99, L"ListView" },  // FileManager DIALOG 99 CAPTION
  { 2101, 2101, L"Language" },  // FileManager DIALOG 2101 CAPTION
  { 2101, 2102, L"Language:" },  // FileManager DIALOG 2101 LTEXT
  { 2103, 543, L"&View:" },  // FileManager DIALOG 2103 LTEXT
  { 2103, 2103, L"Editor" },  // FileManager DIALOG 2103 CAPTION
  { 2103, 2104, L"&Editor:" },  // FileManager DIALOG 2103 LTEXT
  { 2103, 2105, L"&Diff:" },  // FileManager DIALOG 2103 LTEXT
  { 2200, 2200, L"System" },  // FileManager DIALOG 2200 CAPTION
  { 2200, 2201, L"Associate 7-Zip with:" },  // FileManager DIALOG 2200 LTEXT
  { 2300, 2300, L"7-Zip" },  // FileManager DIALOG 2300 CAPTION
  { 2300, 2301, L"Integrate 7-Zip to shell context menu" },  // FileManager DIALOG 2300 CONTROL
  { 2300, 2302, L"Cascaded context menu" },  // FileManager DIALOG 2300 CONTROL
  { 2300, 2303, L"Context menu items:" },  // FileManager DIALOG 2300 LTEXT
  { 2300, 2304, L"Icons in context menu" },  // FileManager DIALOG 2300 CONTROL
  { 2300, 2310, L"(32-bit)" },  // FileManager DIALOG 2300 CONTROL
  { 2300, 3430, L"Eliminate duplication of root folder" },  // FileManager DIALOG 2300 CONTROL
  { 2300, 3440, L"Propagate Zone.Id stream:" },  // FileManager DIALOG 2300 LTEXT
  { 2400, 2400, L"Folders" },  // FileManager DIALOG 2400 CAPTION
  { 2400, 2401, L"&Working folder" },  // FileManager DIALOG 2400 LTEXT
  { 2400, 2402, L"&System temp folder" },  // FileManager DIALOG 2400 CONTROL
  { 2400, 2403, L"&Current" },  // FileManager DIALOG 2400 CONTROL
  { 2400, 2404, L"Specified:" },  // FileManager DIALOG 2400 CONTROL
  { 2400, 2405, L"Use for removable drives only" },  // FileManager DIALOG 2400 CONTROL
  { 2500, 2500, L"Settings" },  // FileManager DIALOG 2500 CAPTION
  { 2500, 2501, L"Show \"..\" item" },  // FileManager DIALOG 2500 CONTROL
  { 2500, 2502, L"Show real file &icons" },  // FileManager DIALOG 2500 CONTROL
  { 2500, 2503, L"Show system &menu" },  // FileManager DIALOG 2500 CONTROL
  { 2500, 2504, L"&Full row select" },  // FileManager DIALOG 2500 CONTROL
  { 2500, 2505, L"Show &grid lines" },  // FileManager DIALOG 2500 CONTROL
  { 2500, 2506, L"&Single-click to open an item" },  // FileManager DIALOG 2500 CONTROL
  { 2500, 2507, L"&Alternative selection mode" },  // FileManager DIALOG 2500 CONTROL
  { 2500, 2508, L"Use &large memory pages" },  // FileManager DIALOG 2500 CONTROL
  { 2900, 2900, L"About 7-Zip" },  // FileManager DIALOG 2900 CAPTION
  { 2900, 2901, L"7-Zip is free software" },  // FileManager DIALOG 2900 LTEXT
  { 3400, 3400, L"Extract" },  // GUI DIALOG 3400 CAPTION
  { 3400, 3401, L"E&xtract to:" },  // GUI DIALOG 3400 LTEXT
  { 3400, 3410, L"Path mode:" },  // GUI DIALOG 3400 LTEXT
  { 3400, 3420, L"Overwrite mode:" },  // GUI DIALOG 3400 LTEXT
  { 3400, 3430, L"Eliminate duplication of root folder" },  // GUI DIALOG 3400 CONTROL
  { 3400, 3431, L"Restore file security" },  // GUI DIALOG 3400 CONTROL
  { 3400, 3803, L"Show Password" },  // GUI DIALOG 3400 CONTROL
  { 3400, 3807, L"Password" },  // GUI DIALOG 3400 GROUPBOX
  { 3500, 440, L"Yes to &All" },  // FileManager DIALOG 3500 PUSHBUTTON
  { 3500, 441, L"No to A&ll" },  // FileManager DIALOG 3500 PUSHBUTTON
  { 3500, 3500, L"Confirm File Replace" },  // FileManager DIALOG 3500 CAPTION
  { 3500, 3501, L"Destination folder already contains processed file." },  // FileManager DIALOG 3500 LTEXT
  { 3500, 3502, L"Would you like to replace the existing file" },  // FileManager DIALOG 3500 LTEXT
  { 3500, 3503, L"with this one?" },  // FileManager DIALOG 3500 LTEXT
  { 3500, 3505, L"A&uto Rename" },  // FileManager DIALOG 3500 PUSHBUTTON
  { 3800, 3800, L"Enter password" },  // FileManager DIALOG 3800 CAPTION
  { 3800, 3801, L"&Enter password:" },  // FileManager DIALOG 3800 LTEXT
  { 3800, 3803, L"&Show password" },  // FileManager DIALOG 3800 CONTROL
  { 4000, 2100, L"Options" },  // GUI DIALOG 4000 PUSHBUTTON
  { 4000, 3410, L"Path mode:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 3801, L"Enter &password:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 3802, L"Reenter password:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 3803, L"Show Password" },  // GUI DIALOG 4000 CONTROL
  { 4000, 4000, L"Add to Archive" },  // GUI DIALOG 4000 CAPTION
  { 4000, 4001, L"&Archive:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4002, L"&Update mode:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4003, L"Archive &format:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4004, L"Compression &level:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4005, L"Compression &method:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4006, L"&Dictionary size:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4007, L"&Word size:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4008, L"&Solid Block size:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4009, L"Number of CPU &threads:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4010, L"Parameters:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4011, L"Options" },  // GUI DIALOG 4000 GROUPBOX
  { 4000, 4012, L"Create SF&X archive" },  // GUI DIALOG 4000 CONTROL
  { 4000, 4013, L"Compress shared files" },  // GUI DIALOG 4000 CONTROL
  { 4000, 4014, L"Encryption" },  // GUI DIALOG 4000 GROUPBOX
  { 4000, 4015, L"&Encryption method:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4016, L"Encrypt file &names" },  // GUI DIALOG 4000 CONTROL
  { 4000, 4017, L"Memory usage for Compressing:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4018, L"Memory usage for Decompressing:" },  // GUI DIALOG 4000 LTEXT
  { 4000, 4019, L"Delete files after compression" },  // GUI DIALOG 4000 CONTROL
  { 4000, 7302, L"Split to &volumes, bytes:" },  // GUI DIALOG 4000 LTEXT
  { 6602, 6602, L"7-Zip: Diagnostic messages" },  // FileManager DIALOG 6602 CAPTION
  { 7300, 7300, L"Split File" },  // FileManager DIALOG 7300 CAPTION
  { 7300, 7301, L"&Split to:" },  // FileManager DIALOG 7300 LTEXT
  { 7300, 7302, L"Split to &volumes,  bytes:" },  // FileManager DIALOG 7300 LTEXT
  { 7600, 442, L"&Stop" },  // GUI DIALOG 7600 PUSHBUTTON
  { 7600, 443, L"&Restart" },  // GUI DIALOG 7600 PUSHBUTTON
  { 7600, 1007, L"Size" },  // GUI DIALOG 7600 RTEXT
  { 7600, 3900, L"Elapsed time:" },  // GUI DIALOG 7600 LTEXT
  { 7600, 3903, L"Speed" },  // GUI DIALOG 7600 RTEXT
  { 7600, 4006, L"&Dictionary size:" },  // GUI DIALOG 7600 LTEXT
  { 7600, 4009, L"&Number of CPU threads:" },  // GUI DIALOG 7600 LTEXT
  { 7600, 7600, L"Benchmark" },  // GUI DIALOG 7600 CAPTION
  { 7600, 7601, L"Memory usage:" },  // GUI DIALOG 7600 LTEXT
  { 7600, 7602, L"Compressing" },  // GUI DIALOG 7600 GROUPBOX
  { 7600, 7603, L"Decompressing" },  // GUI DIALOG 7600 GROUPBOX
  { 7600, 7604, L"Rating" },  // GUI DIALOG 7600 RTEXT
  { 7600, 7605, L"Total Rating" },  // GUI DIALOG 7600 GROUPBOX
  { 7600, 7606, L"Current" },  // GUI DIALOG 7600 LTEXT
  { 7600, 7607, L"Resulting" },  // GUI DIALOG 7600 LTEXT
  { 7600, 7608, L"CPU Usage" },  // GUI DIALOG 7600 RTEXT
  { 7600, 7609, L"Rating / Usage" },  // GUI DIALOG 7600 RTEXT
  { 7600, 7610, L"Passes:" },  // GUI DIALOG 7600 LTEXT
  { 7699, 3900, L"Elapsed time:" },  // GUI DIALOG 7699 LTEXT
  { 7699, 7699, L"Benchmark" },  // GUI DIALOG 7699 CAPTION
  { 7700, 7700, L"Link" },  // FileManager DIALOG 7700 CAPTION
  { 7700, 7701, L"Link" },  // FileManager DIALOG 7700 DEFPUSHBUTTON
  { 7700, 7702, L"Link from:" },  // FileManager DIALOG 7700 LTEXT
  { 7700, 7703, L"Link to:" },  // FileManager DIALOG 7700 LTEXT
  { 7700, 7710, L"Link Type" },  // FileManager DIALOG 7700 GROUPBOX
  { 7700, 7711, L"Hard Link" },  // FileManager DIALOG 7700 CONTROL
  { 7700, 7712, L"File Symbolic Link" },  // FileManager DIALOG 7700 CONTROL
  { 7700, 7713, L"Directory Symbolic Link" },  // FileManager DIALOG 7700 CONTROL
  { 7700, 7714, L"Directory Junction" },  // FileManager DIALOG 7700 CONTROL
  { 7700, 7715, L"WSL" },  // FileManager DIALOG 7700 CONTROL
  { 7800, 7800, L"Memory usage request" },  // FileManager DIALOG 7800 CAPTION
  { 7800, 7801, L"Change allowed limit for next operations" },  // FileManager DIALOG 7800 CONTROL
  { 7800, 7802, L"&Repeat selected action for current operation" },  // FileManager DIALOG 7800 CONTROL
  { 7800, 7803, L"Action" },  // FileManager DIALOG 7800 GROUPBOX
  { 7800, 7820, L"&Allow archive unpacking" },  // FileManager DIALOG 7800 CONTROL
  { 7800, 7821, L"&Skip archive unpacking" },  // FileManager DIALOG 7800 CONTROL
  { 14001, 4040, L"Store symbolic links" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4041, L"Store hard links" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4042, L"Store alternate data streams" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4043, L"Store file security" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4080, L"Time" },  // GUI DIALOG 14001 GROUPBOX
  { 14001, 4081, L"Timestamp precision:" },  // GUI DIALOG 14001 LTEXT
  { 14001, 4082, L"Store modification time" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4083, L"Store creation time" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4084, L"Store last access time" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4085, L"Set archive time to latest file time" },  // GUI DIALOG 14001 CONTROL
  { 14001, 4086, L"Do not change source files last access time" },  // GUI DIALOG 14001 CONTROL
  { 14001, 14001, L"Options" },  // GUI DIALOG 14001 CAPTION
};
