// SZLang.mm -- see SZLang.h. The parser is the engine's own CLang (CPP/Common/Lang.cpp), so
// the positional / consume-an-ID rules are exactly 7zFM's. This file also installs the
// MyLoadString hook used by the platform layer.

#import "SZLang.h"
#import "SZSettings.h"
#import "SZError.h"
#import "Internal/SZBridgeUtils.h"

#include <mutex>

@implementation SZLanguageInfo
- (instancetype)initWithCode:(NSString *)code path:(NSString *)path english:(NSString *)english native:(NSString *)native count:(NSInteger)count
                    comments:(NSArray<NSString *> *)comments missing:(NSArray<NSString *> *)missing extra:(NSArray<NSString *> *)extra
{
  self = [super init];
  if (!self)
    return nil;
  _code = [code copy];
  _path = [path copy];
  _englishName = [english copy];
  _nativeName = [native copy];
  _stringCount = count;
  _comments = [comments copy];
  _missingLines = [missing copy];
  _extraLines = [extra copy];
  return self;
}
- (NSString *)description
{
  return [NSString stringWithFormat:@"<SZLanguageInfo %@ %@ / %@ (%lu)>", _code, _englishName, _nativeName, (unsigned long)_stringCount];
}
@end

static const wchar_t *SZLangHook(UInt32 langID);

// English resource strings that exist in the Windows string tables but not in Lang/en.ttt
// (PropertyName.rc IDS_PROP_* entries the translations never carried). MyLoadString falls
// back to these after the lang file and en.ttt, like the Win32 resource would.
struct SZResourceString { UInt32 id; const wchar_t *text; };
static const SZResourceString kResourceOnlyStrings[] =
{
  { 1019, L"CRC" },
  { 1067, L"SHA-1" },
  { 1068, L"SHA-256" },
  { 1084, L"Is not archive type" },
  { 1085, L"Physical Size can't be detected" },
  { 1086, L"Zeros Tail Is Allowed" },
  { 1092, L"Stream ID" },
  { 1094, L"Out Name" },
  { 1096, L"ArcFileName" },
  { 1097, L"IsHash" },
  { 1099, L"User ID" },
  { 1100, L"Group ID" },
  { 1101, L"Device Major" },
  { 1102, L"Device Minor" },
  { 1103, L"Dev Major" },
  { 1104, L"Dev Minor" },
};

// The English of the .rc resources themselves (winmatch): with no language file 7zFM shows these,
// not Lang/en.ttt, which differs in case and wording in places ("Add to Archive" / "Add to
// archive"). Generated by Mac/scripts/make-rc-strings.py.
struct SZRcString { UInt32 id; const wchar_t *text; };
struct SZRcDialogString { UInt32 dialog; UInt32 id; const wchar_t *text; };
#include "Internal/SZRcStrings.h"

static const wchar_t *SZRcStringFor(UInt32 langID)
{
  size_t lo = 0, hi = sizeof(kSZRcStrings) / sizeof(kSZRcStrings[0]);
  while (lo < hi)
  {
    const size_t mid = (lo + hi) / 2;
    if (kSZRcStrings[mid].id == langID)
      return kSZRcStrings[mid].text;
    if (kSZRcStrings[mid].id < langID) lo = mid + 1; else hi = mid;
  }
  return NULL;
}

static const wchar_t *SZRcDialogStringFor(UInt32 dialogID, UInt32 langID)
{
  for (const SZRcDialogString &r : kSZRcDialogStrings)
    if (r.dialog == dialogID && r.id == langID)
      return r.text;
  return NULL;
}

static const wchar_t *SZResourceOnlyString(UInt32 langID)
{
  for (const SZResourceString &r : kResourceOnlyStrings)
    if (r.id == langID)
      return r.text;
  return NULL;
}

@implementation SZLang
{
  CLang _english;
  CLang _current;
  std::mutex _mutex;
  NSString *_currentCode;
  NSArray<NSString *> *_comments;
  NSArray<SZLanguageInfo *> *_available;
  NSArray<NSString *> *_failedFiles;
}

+ (void)load
{
  g_SZ_LoadStringHook = SZLangHook;
}

+ (SZLang *)shared
{
  static SZLang *shared = nil;
  static dispatch_once_t once;
  dispatch_once(&once, ^{ shared = [[SZLang alloc] initPrivate]; });
  return shared;
}

- (instancetype)initPrivate
{
  self = [super init];
  if (!self)
    return nil;
  _currentCode = @"";
  _comments = @[];
  NSString *en = [[SZLang langDirectoryPath] stringByAppendingPathComponent:@"en.ttt"];
  if (![[NSFileManager defaultManager] fileExistsAtPath:en] || !_english.Open([en fileSystemRepresentation], "7-Zip"))
    NSLog(@"SevenZipKit: built-in English lang table not found at %@", en);
  return self;
}

+ (NSString *)langDirectoryPath
{
  NSBundle *bundle = [NSBundle bundleForClass:[SZLang class]];
  NSString *dir = [bundle pathForResource:@"Lang" ofType:nil];
  if (!dir)
    dir = [[bundle resourcePath] stringByAppendingPathComponent:@"Lang"];
  return dir;
}

- (const wchar_t *)wideStringForID:(uint32_t)langID
{
  std::lock_guard<std::mutex> lock(_mutex);
  const wchar_t *s = _current.IsEmpty() ? NULL : _current.Get(langID);
  if (!s)
    s = SZRcStringFor(langID);
  if (!s)
    s = _english.Get(langID);
  if (!s)
    s = SZResourceOnlyString(langID);
  return s;
}

- (NSString *)stringForID:(uint32_t)langID inDialog:(uint32_t)dialogID colon:(BOOL)colon fallback:(NSString *)fallback
{
  {
    std::lock_guard<std::mutex> lock(_mutex);
    const wchar_t *t = _current.IsEmpty() ? NULL : _current.Get(langID);
    if (t)
    {
      NSString *text = SZStringFromWChars(t, (unsigned)wcslen(t));
      return colon ? [text stringByAppendingString:@":"] : text;
    }
  }
  const wchar_t *r = SZRcDialogStringFor(dialogID, langID);
  if (r)
    return SZStringFromWChars(r, (unsigned)wcslen(r));
  return [self stringForID:langID fallback:fallback];
}

- (NSString *)stringForID:(uint32_t)langID
{
  const wchar_t *s = [self wideStringForID:langID];
  return s ? SZStringFromWChars(s, (unsigned)wcslen(s)) : @"";
}

- (NSString *)stringForID:(uint32_t)langID fallback:(NSString *)fallback
{
  const wchar_t *s = [self wideStringForID:langID];
  return s ? SZStringFromWChars(s, (unsigned)wcslen(s)) : fallback;
}

- (NSString *)translatedStringForID:(uint32_t)langID
{
  std::lock_guard<std::mutex> lock(_mutex);
  if (_current.IsEmpty())
    return nil;
  const wchar_t *s = _current.Get(langID);
  return s ? SZStringFromWChars(s, (unsigned)wcslen(s)) : nil;
}

- (NSString *)englishStringForID:(uint32_t)langID
{
  std::lock_guard<std::mutex> lock(_mutex);
  const wchar_t *s = _english.Get(langID);
  if (!s)
    s = SZResourceOnlyString(langID);
  return s ? SZStringFromWChars(s, (unsigned)wcslen(s)) : @"";
}

- (NSInteger)englishStringCount
{
  return _english._ids.Size();
}

- (NSString *)currentLanguageCode
{
  return _currentCode;
}

- (NSArray<NSString *> *)comments
{
  return _comments;
}

- (BOOL)loadLanguageFile:(NSString *)path error:(NSError **)error
{
  CLang lang;
  if (![[NSFileManager defaultManager] fileExistsAtPath:path])
  {
    if (error)
      *error = [SZErrors errorWithCode:SZErrorCodeFileNotFound message:[NSString stringWithFormat:@"Language file not found: %@", path]];
    return NO;
  }
  if (!lang.Open([path fileSystemRepresentation], "7-Zip"))
  {
    if (error)
      *error = [SZErrors errorWithCode:SZErrorCodeInvalidArgument message:[NSString stringWithFormat:@"Not a valid 7-Zip language file: %@", path]];
    return NO;
  }
  NSMutableArray *comments = [NSMutableArray array];
  FOR_VECTOR (i, lang.Comments)
    [comments addObject:SZStringFromUString(lang.Comments[i])];
  {
    std::lock_guard<std::mutex> lock(_mutex);
    _current.Clear();
    // CLang has no move/swap: re-open into the member (the file was just validated)
    _current.Open([path fileSystemRepresentation], "7-Zip");
    _comments = comments;
    _currentCode = [[path lastPathComponent] stringByDeletingPathExtension];
  }
  return YES;
}

- (void)unloadLanguage
{
  std::lock_guard<std::mutex> lock(_mutex);
  _current.Clear();
  _comments = @[];
  _currentCode = @"";
}

- (BOOL)loadLanguageWithCode:(NSString *)code error:(NSError **)error
{
  NSString *dir = [SZLang langDirectoryPath];
  if (code.length == 0)
  {
    // OpenDefaultLang (LangUtils.cpp:279-306): try the system language candidates
    for (NSString *candidate in [SZLang systemLanguageCandidates])
    {
      NSString *path = [dir stringByAppendingPathComponent:[candidate stringByAppendingPathExtension:@"txt"]];
      if ([[NSFileManager defaultManager] fileExistsAtPath:path] && [self loadLanguageFile:path error:NULL])
        return YES;
    }
    [self unloadLanguage];
    return YES;
  }
  if ([code isEqualToString:@"-"] || [code containsString:@"/"])
  {
    [self unloadLanguage];   // "-" = built-in English; a path separator is ignored (LangUtils.cpp:311-330)
    return YES;
  }
  NSString *file = [code containsString:@"."] ? code : [code stringByAppendingPathExtension:@"txt"];
  NSString *path = [dir stringByAppendingPathComponent:file];
  if ([self loadLanguageFile:path error:error])
    return YES;
  [self unloadLanguage];
  return NO;
}

static NSString *SZLangLine(UInt32 langID, const wchar_t *text)
{
  // LangPage.cpp:228-240: n.Add_UInt32(id); n += " : "; n += text;
  NSString *body = text ? SZStringFromWChars(text, (unsigned)wcslen(text)) : @"";
  return [NSString stringWithFormat:@"%u : %@", (unsigned)langID, body];
}

- (NSArray<SZLanguageInfo *> *)languagesInDirectory:(NSString *)dir failedFiles:(NSArray<NSString *> **)failedFiles
{
  NSArray<NSString *> *files = [[NSFileManager defaultManager] contentsOfDirectoryAtPath:dir error:NULL] ?: @[];
  NSMutableArray *result = [NSMutableArray array];
  NSMutableArray<NSString *> *failed = [NSMutableArray array];
  for (NSString *file in [files sortedArrayUsingSelector:@selector(compare:)])
  {
    // LangPage.cpp:108-115: only *.txt, compared case-blind.
    if ([[file pathExtension] caseInsensitiveCompare:@"txt"] != NSOrderedSame)
      continue;
    NSString *path = [dir stringByAppendingPathComponent:file];
    BOOL isDir = NO;
    if ([[NSFileManager defaultManager] fileExistsAtPath:path isDirectory:&isDir] && isDir)
      continue;
    CLang lang;
    if (!lang.Open([path fileSystemRepresentation], "7-Zip"))
    {
      [failed addObject:file];
      continue;
    }
    const wchar_t *en = lang.Get(1);
    const wchar_t *native = lang.Get(2);

    NSMutableArray<NSString *> *comments = [NSMutableArray array];
    FOR_VECTOR (k, lang.Comments)
      [comments addObject:SZStringFromUString(lang.Comments[k])];

    // The merge walk of LangPage.cpp:197-245 over the two sorted id lists.
    NSMutableArray<NSString *> *missing = [NSMutableArray array];
    NSMutableArray<NSString *> *extra = [NSMutableArray array];
    unsigned numLines = lang._ids.Size();
    {
      std::lock_guard<std::mutex> lock(_mutex);
      if (!_english.IsEmpty())
      {
        numLines = 0;
        unsigned i1 = 0, i2 = 0;
        for (;;)
        {
          const bool d1 = i1 < _english._ids.Size();
          const bool d2 = i2 < lang._ids.Size();
          if (!d1 && !d2)
            break;
          const UInt32 id1 = d1 ? _english._ids[i1] : (UInt32)0 - 1;
          const UInt32 id2 = d2 ? lang._ids[i2] : (UInt32)0 - 1;
          if (d1 && d2 && id1 == id2)
          {
            i1++;
            i2++;
            numLines++;
            continue;
          }
          const bool id1IsSmaller = d1 && (!d2 || id1 < id2);
          if (id1IsSmaller)
          {
            [missing addObject:SZLangLine(id1, _english.Get_by_index(i1))];
            i1++;
          }
          else
          {
            [extra addObject:SZLangLine(id2, lang.Get_by_index(i2))];
            i2++;
          }
        }
        numLines += (unsigned)extra.count;   // langInfo.NumLines = numLines + ExtraLines.Size()
      }
    }
    [result addObject:[[SZLanguageInfo alloc] initWithCode:[file stringByDeletingPathExtension] path:path
                                                   english:en ? SZStringFromWChars(en, (unsigned)wcslen(en)) : @""
                                                    native:native ? SZStringFromWChars(native, (unsigned)wcslen(native)) : @""
                                                     count:numLines
                                                  comments:comments missing:missing extra:extra]];
  }
  if (failedFiles)
    *failedFiles = failed;
  return result;
}

- (NSArray<SZLanguageInfo *> *)availableLanguages
{
  if (_available)
    return _available;
  NSArray<NSString *> *failed = nil;
  _available = [self languagesInDirectory:[SZLang langDirectoryPath] failedFiles:&failed];
  _failedFiles = failed ?: @[];
  return _available;
}

- (NSArray<NSString *> *)failedLanguageFiles
{
  [self availableLanguages];
  return _failedFiles;
}

+ (NSArray<NSString *> *)systemLanguageCandidates
{
  // Lang_GetShortNames_for_DefaultLang (LangUtils.cpp:169-277) mapped to BCP-47 input.
  NSMutableArray *result = [NSMutableArray array];
  NSArray<NSString *> *preferred = [NSLocale preferredLanguages];
  NSString *first = preferred.count ? preferred[0] : @"en";
  NSDictionary *comps = [NSLocale componentsFromLocaleIdentifier:first];
  NSString *lang = [comps[NSLocaleLanguageCode] lowercaseString] ?: @"en";
  NSString *script = comps[NSLocaleScriptCode] ?: @"";
  NSString *region = [comps[NSLocaleCountryCode] lowercaseString] ?: @"";

  if ([lang isEqualToString:@"zh"])
  {
    if ([script isEqualToString:@"Hant"] || [region isEqualToString:@"tw"] || [region isEqualToString:@"hk"] || [region isEqualToString:@"mo"])
      [result addObject:@"zh-tw"];
    else
      [result addObject:@"zh-cn"];
  }
  else if ([lang isEqualToString:@"sr"])
    [result addObject:[script isEqualToString:@"Latn"] ? @"sr-spl" : @"sr-spc"];
  else if ([lang isEqualToString:@"uz"])
  {
    if ([script isEqualToString:@"Cyrl"])
      [result addObject:@"uz-cyrl"];
    [result addObject:@"uz"];
  }
  else if ([lang isEqualToString:@"pt"])
  {
    if ([region isEqualToString:@"br"])
      [result addObject:@"pt-br"];
    [result addObject:@"pt"];
  }
  else if ([lang isEqualToString:@"pa"])
    [result addObject:@"pa-in"];
  else if ([lang isEqualToString:@"ckb"])
    [result addObject:@"ku-ckb"];
  else if ([lang isEqualToString:@"no"] || [lang isEqualToString:@"nb"])
    [result addObject:@"nb"];
  else
  {
    if (region.length)
      [result addObject:[NSString stringWithFormat:@"%@-%@", lang, region]];
    [result addObject:lang];
  }
  return result;
}

@end

static const wchar_t *SZLangHook(UInt32 langID)
{
  return [[SZLang shared] wideStringForID:langID];
}
