// URLCommandPolicyTests.swift -- sec113: the URL secret and the allow-list a `sevenzip:///run` URL
// must pass (`URLCommandPolicy.swift`).
//
// Every legitimate shape is generated by `FinderMenuModel` itself -- every Finder menu item, both
// Quick Actions, under every setting that changes a switch, inline and with a list file -- so a
// change to the menu that the policy does not follow fails here. The forged URLs are the ones an
// attacker would send: no or a wrong token, `-o` into `~/Library/LaunchAgents`, `..`, a symbolic
// link out of the archive's folder, `-sdel`, `-p`, `-y`, `-ao*`, `-sfx`, `u`, `d`, `e`, foreign
// list files.

import XCTest

final class URLCommandPolicyTests: XCTestCase {

    private var root = ""
    private var home = ""
    private var downloads = ""
    private var launchAgents = ""
    private var extensionTemp = ""
    private var policy: URLCommandPolicy!

    override func setUpWithError() throws {
        let fm = FileManager.default
        // realpath: NSTemporaryDirectory is under /var, which is a link to /private/var.
        let temp = try XCTUnwrap(URLCommandPolicy.realPath(NSTemporaryDirectory()))
        root = (temp as NSString).appendingPathComponent("sec113-\(UUID().uuidString)")
        home = root + "/home"
        downloads = home + "/Downloads"
        launchAgents = home + "/Library/LaunchAgents"
        extensionTemp = home + "/Library/Containers/\(SevenZipBundle.finderSync)/Data/tmp"
        for dir in [downloads, launchAgents, extensionTemp, downloads + "/folder",
                    home + "/Library/Mobile Documents/com~apple~CloudDocs"] {
            try fm.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }
        for file in ["test.7z", "two.zip", "notes.txt", "sums.sha256", "evil.7z", "folder/inner.txt"] {
            XCTAssertTrue(fm.createFile(atPath: downloads + "/" + file, contents: Data("x".utf8)))
        }
        XCTAssertTrue(fm.createFile(atPath: launchAgents + "/planted.zip", contents: Data("x".utf8)))
        XCTAssertTrue(fm.createFile(atPath: home + "/Library/Mobile Documents/com~apple~CloudDocs/cloud.7z",
                                    contents: Data("x".utf8)))
        // `evil/` next to `evil.7z` is a link into LaunchAgents: "Extract to evil/" would write there.
        try fm.createSymbolicLink(atPath: downloads + "/evil", withDestinationPath: launchAgents)
        policy = URLCommandPolicy(homeDirectory: home, listFileDirectories: [extensionTemp])
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(atPath: root)
    }

    private func selection(_ names: [String], in folder: String? = nil) -> FinderSelection {
        let dir = folder ?? downloads
        let paths = names.map { dir + "/" + $0 }
        return FinderSelection(paths: paths, directoryFlags: paths.map {
            var isDir: ObjCBool = false
            return FileManager.default.fileExists(atPath: $0, isDirectory: &isDir) && isDir.boolValue
        })
    }

    private func assertRefused(_ argv: [String], tmp: [String] = [], _ message: String = "",
                               file: StaticString = #filePath, line: UInt = #line) {
        let decision = policy.evaluate(argv: argv, temporaryFiles: tmp)
        XCTAssertFalse(decision.isAllowed, "\(message): \(argv) was allowed", file: file, line: line)
    }

    private func assertAllowed(_ argv: [String], tmp: [String] = [], _ message: String = "",
                               file: StaticString = #filePath, line: UInt = #line) {
        let decision = policy.evaluate(argv: argv, temporaryFiles: tmp)
        XCTAssertTrue(decision.isAllowed, "\(message): \(argv) was refused: \(decision)", file: file, line: line)
    }

    // MARK: - The token

    func testTokenFormatAndConstantTimeComparison() {
        let a = String(repeating: "a1", count: 32)
        XCTAssertTrue(URLCommandToken.isWellFormed(a))
        XCTAssertFalse(URLCommandToken.isWellFormed(nil))
        XCTAssertFalse(URLCommandToken.isWellFormed(String(a.dropLast())))
        XCTAssertFalse(URLCommandToken.isWellFormed(a.uppercased()))
        XCTAssertFalse(URLCommandToken.isWellFormed(String(repeating: "g", count: 64)))

        XCTAssertTrue(URLCommandToken.matches(a, expected: a))
        XCTAssertFalse(URLCommandToken.matches(nil, expected: a), "no token")
        XCTAssertFalse(URLCommandToken.matches("", expected: a), "empty token")
        XCTAssertFalse(URLCommandToken.matches(String(repeating: "b2", count: 32), expected: a), "wrong token")
        XCTAssertFalse(URLCommandToken.matches(String(a.dropLast()) + "0", expected: a), "last digit differs")
        XCTAssertFalse(URLCommandToken.matches(a, expected: nil), "the app has no token")
        XCTAssertFalse(URLCommandToken.matches("x", expected: "x"), "a malformed expected token never matches")
        XCTAssertEqual(URLCommandToken.hex([0x00, 0x0f, 0xa0, 0xff]), "000fa0ff")
    }

    func testTokenTravelsInTheRunURL() throws {
        let token = String(repeating: "0f", count: 32)
        let url = try XCTUnwrap(CommandURL.url(argv: ["t", "-an", "-aiw-!/tmp/a.7z"], token: token))
        XCTAssertEqual(CommandURL.token(in: url), token)
        guard case .run(let argv, _) = try CommandURL.parse(url) else { return XCTFail("not run") }
        XCTAssertEqual(argv, ["t", "-an", "-aiw-!/tmp/a.7z"])

        XCTAssertNil(CommandURL.token(in: try XCTUnwrap(CommandURL.url(argv: ["t"]))), "no token")
        // Two token items are ambiguous: no token.
        let doubled = try XCTUnwrap(URL(string: url.absoluteString + "&token=" + token))
        XCTAssertNil(CommandURL.token(in: doubled))
        // `x-7zip:` carries it the same way.
        let alternate = try XCTUnwrap(URL(string: url.absoluteString.replacingOccurrences(of: "sevenzip:", with: "x-7zip:")))
        XCTAssertEqual(CommandURL.token(in: alternate), token)
    }

    func testTheExtensionReadsTheTokenFromItsSnapshot() throws {
        // The snapshot file the app pushes into an extension container, read the way the
        // extension reads it.
        let file = URL(fileURLWithPath: root + "/snapshot.plist")
        let token = String(repeating: "c3", count: 32)
        var dict = IntegrationSettings().dictionary
        dict[URLCommandToken.settingsKey] = token
        try PropertyListSerialization.data(fromPropertyList: dict, format: .xml, options: 0).write(to: file)
        XCTAssertEqual(IntegrationSettings.snapshotDictionary(at: file)?[URLCommandToken.settingsKey] as? String, token)
        XCTAssertEqual(IntegrationSettings.load(fromSnapshotAt: file), IntegrationSettings(),
                       "the secret is not one of the menu settings")
    }

    // MARK: - Every legitimate shape is accepted

    /// Every command the Finder menu offers for `sel`, under every switch-changing setting, inline.
    private func assertEveryMenuCommandAllowed(_ sel: FinderSelection, file: StaticString = #filePath,
                                               line: UInt = #line) {
        for settings in URLCommandPolicy.settingVariants() {
            let commands = FinderMenuModel.allCommands(selection: sel, settings: settings)
            XCTAssertFalse(commands.isEmpty, file: file, line: line)
            // C13 "Test : Checksum" is offered for a folder too and refused when chosen
            // (`refusesDirectories`, ContextMenu.cpp:1280); the policy refuses it up front.
            for command in commands where !(command.refusesDirectories && sel.directoryFlags.contains(true)) {
                let built = command.argv(for: sel.paths, listFileDirectory: extensionTemp)
                let decision = policy.evaluate(argv: built.argv, temporaryFiles: built.temporaryFiles)
                XCTAssertEqual(decision, .allow(argv: built.argv, temporaryFiles: []),
                               "\(command.verb) \(built.argv)", file: file, line: line)
            }
        }
    }

    func testEveryFinderMenuCommandForOneArchive() {
        assertEveryMenuCommandAllowed(selection(["test.7z"]))
    }

    func testEveryFinderMenuCommandForSeveralArchives() {
        assertEveryMenuCommandAllowed(selection(["test.7z", "two.zip"]))
    }

    func testEveryFinderMenuCommandForFilesAndFolders() {
        assertEveryMenuCommandAllowed(selection(["notes.txt"]))
        assertEveryMenuCommandAllowed(selection(["folder"]))
        assertEveryMenuCommandAllowed(selection(["folder", "notes.txt", "test.7z"]))
        assertEveryMenuCommandAllowed(selection(["sums.sha256"]))
    }

    func testEveryCommandInTheMenuTreeItself() {
        // The tree Finder shows (flags, cascading), not only `allCommands`.
        let sel = selection(["test.7z"])
        for cascaded in [true, false] {
            var settings = IntegrationSettings()
            settings.cascadedMenu = cascaded
            settings.writeZoneIdExtract = 1
            for command in FinderMenuModel.flattenCommands(FinderMenuModel.build(selection: sel, settings: settings)) {
                let built = command.argv(for: sel.paths, listFileDirectory: extensionTemp)
                assertAllowed(built.argv, tmp: built.temporaryFiles, command.verb)
            }
        }
    }

    func testBothQuickActions() throws {
        for verb in ["SevenZipExtractTo", "SevenZipCompress"] {
            for settings in URLCommandPolicy.settingVariants() {
                let sel = selection(verb == "SevenZipCompress" ? ["folder", "notes.txt"] : ["test.7z"])
                let command = try XCTUnwrap(FinderMenuModel.command(verb: verb, selection: sel, settings: settings))
                let built = command.argv(for: sel.paths, listFileDirectory: extensionTemp)
                assertAllowed(built.argv, tmp: built.temporaryFiles, verb)
            }
        }
    }

    func testOpenArchiveShapes() {
        assertAllowed([downloads + "/test.7z"], "A1 Open archive")
        for type in ArchiveNaming.openTypes where !type.isEmpty {
            assertAllowed([downloads + "/test.7z", "-t" + type], "A2 Open archive > \(type)")
        }
        assertRefused([downloads + "/test.7z", "-tiso"], "a type the menu does not offer")
        assertRefused([downloads + "/test.7z", "-t7z", "-y"], "extra arguments")
        assertRefused([downloads + "/../Downloads/test.7z"], "..")
    }

    func testLongSelectionThroughAListFileIsReadAndInlined() throws {
        var names: [String] = []
        for i in 0..<20 {
            let name = "item \(i).txt"
            XCTAssertTrue(FileManager.default.createFile(atPath: downloads + "/" + name, contents: Data()))
            names.append(name)
        }
        let sel = selection(names)
        let command = try XCTUnwrap(FinderMenuModel.command(verb: "SevenZipCompressTo7z", selection: sel))
        let built = command.argv(for: sel.paths, listFileDirectory: extensionTemp)
        XCTAssertEqual(built.temporaryFiles.count, 1, "20 items go into a list file")
        let decision = policy.evaluate(argv: built.argv, temporaryFiles: built.temporaryFiles)
        let inline = command.prefixArguments + sel.paths.map { "-iw-!" + $0 } + command.suffixArguments
        XCTAssertEqual(decision, .allow(argv: inline, temporaryFiles: built.temporaryFiles))

        // The same list, not declared in `tmp`, or in a folder the extensions do not use.
        assertRefused(built.argv, tmp: [], "undeclared list file")
        let foreign = try XCTUnwrap(CommandURL.writeListFile(paths: sel.paths, in: downloads))
        assertRefused(command.prefixArguments + ["-iw-@" + foreign] + command.suffixArguments, tmp: [foreign],
                      "list file outside the extensions' temporary folders")
        // A link named like a list file.
        let link = extensionTemp + "/7zL-\(UUID().uuidString).txt"
        try FileManager.default.createSymbolicLink(atPath: link, withDestinationPath: foreign)
        assertRefused(command.prefixArguments + ["-iw-@" + link] + command.suffixArguments, tmp: [link],
                      "a list file that is a symbolic link")
        // Not the generated name.
        let named = extensionTemp + "/list.txt"
        try FileManager.default.copyItem(atPath: foreign, toPath: named)
        assertRefused(command.prefixArguments + ["-iw-@" + named] + command.suffixArguments, tmp: [named],
                      "a list file without the 7zL-<uuid> name")
    }

    func testDocumentFoldersInLibraryAreAllowed() {
        let cloud = home + "/Library/Mobile Documents/com~apple~CloudDocs"
        let sel = selection(["cloud.7z"], in: cloud)
        let command = FinderMenuModel.command(verb: "SevenZipExtractHere", selection: sel)!
        assertAllowed(command.argv(for: sel.paths).argv, "iCloud Drive")
    }

    // MARK: - Forged commands are refused

    func testExtractIntoLaunchAgentsIsRefused() {
        let archive = downloads + "/test.7z"
        assertRefused(["x", "-o" + launchAgents + "/", "-an", "-aiw-!" + archive], "-o elsewhere")
        assertRefused(["x", "-o" + launchAgents + "/", "-y", "-an", "-aiw-!" + archive], "-o elsewhere with -y")
        // The legitimate shape, but the archive itself sits in LaunchAgents.
        let planted = selection(["planted.zip"], in: launchAgents)
        let here = FinderMenuModel.command(verb: "SevenZipExtractHere", selection: planted)!
        assertRefused(here.argv(for: planted.paths).argv, "Extract Here inside ~/Library")
        // Under the archive's folder, but through `..`.
        assertRefused(["x", "-o" + downloads + "/../Library/LaunchAgents/", "-an", "-aiw-!" + archive], "..")
        assertRefused(["x", "-o" + downloads + "/test/", "-an", "-aiw-!" + downloads + "/x/../test.7z"],
                      ".. in the selection")
    }

    func testSymbolicLinkEscapeIsRefused() {
        // "Extract to evil/" is the menu's own shape for evil.7z, but evil/ links to LaunchAgents.
        let sel = selection(["evil.7z"])
        let command = FinderMenuModel.command(verb: "SevenZipExtractTo", selection: sel)!
        let argv = command.argv(for: sel.paths).argv
        XCTAssertTrue(argv[1].hasPrefix("-o" + downloads + "/evil/"), argv[1])
        assertRefused(argv, "the -o folder is a link into ~/Library")
        // Selecting the link itself.
        let linked = FinderSelection(paths: [downloads + "/evil"], directoryFlags: [false])
        let add = FinderMenuModel.command(verb: "SevenZipCompressTo7z", selection: linked)!
        assertRefused(add.argv(for: linked.paths).argv, "a selected link into ~/Library")
    }

    func testDestructiveAndUnusedSwitchesAreRefused() {
        let item = downloads + "/notes.txt"
        let base = ["a", "-iw-!" + item, "-t7z", "-sae", "--", downloads + "/notes.7z"]
        assertAllowed(base, "B7 itself")
        assertRefused(["a", "-iw-!" + item, "-t7z", "-sae", "-sdel", "--", downloads + "/notes.7z"], "-sdel")
        assertRefused(["a", "-iw-!" + item, "-t7z", "-psecret", "-sae", "--", downloads + "/notes.7z"], "-p")
        assertRefused(["a", "-iw-!" + item, "-t7z", "-sae", "-y", "--", downloads + "/notes.7z"], "-y")
        assertRefused(["a", "-iw-!" + item, "-t7z", "-sfx", "--", downloads + "/notes.7z"], "-sfx")
        assertRefused(["a", "-iw-!" + item, "-ttar", "-sae", "--", downloads + "/notes.7z"], "-t with another type")
        assertRefused(["a", "-iw-!" + item, "-t7z", "-sae", "--", downloads + "/other.7z"], "another archive name")
        assertRefused(["a", "-i!" + item, "-t7z", "-sae", "--", downloads + "/notes.7z"], "wildcard -i!")
        assertRefused(["a", "-r", "-iw-!" + item, "-t7z", "-sae", "--", downloads + "/notes.7z"], "-r")
        assertRefused(["a", "-iw-!" + item, "-xw-!" + item, "-t7z", "-sae", "--", downloads + "/notes.7z"], "-x")

        let archive = downloads + "/test.7z"
        assertRefused(["x", "-o" + downloads + "/test/", "-aoa", "-an", "-aiw-!" + archive], "-aoa")
        assertRefused(["x", "-o" + downloads + "/test/", "-ptest", "-an", "-aiw-!" + archive], "-p on extract")
        assertRefused(["e", "-o" + downloads + "/", "-an", "-aiw-!" + archive], "e")
        assertRefused(["u", "-iw-!" + item, "--", archive], "u")
        assertRefused(["d", "-iw-!" + item, "--", archive], "d")
        assertRefused(["rn", archive, "a", "b"], "rn")
        assertRefused(["b"], "b")
        assertRefused(["l", archive], "l")
        assertRefused(["x", "-o" + downloads + "/test/", "-an", "-ai@" + downloads + "/list.txt"], "-ai@")
        assertRefused(["x", "-o" + downloads + "/test/", "-an", "-aiw-!" + downloads + "/folder"],
                      "extract with a folder selected")
        assertRefused(["x", "-o" + downloads + "/test/", "-an", "-aiw-!" + downloads + "/missing.7z"],
                      "an item that does not exist")
        assertRefused([], "empty")
        assertRefused(["x"], "no selection")
    }

    func testProtectionRules() {
        XCTAssertTrue(policy.isProtected(home + "/Library"))
        XCTAssertTrue(policy.isProtected(home + "/Library/LaunchAgents/x.plist"))
        XCTAssertTrue(policy.isProtected(home + "/Library/Containers/com.example/Data"))
        XCTAssertFalse(policy.isProtected(home + "/Library/Mobile Documents/x"))
        XCTAssertFalse(policy.isProtected(home + "/Library/CloudStorage/Dropbox/x"))
        XCTAssertFalse(policy.isProtected(home + "/LibraryX"))
        XCTAssertFalse(policy.isProtected(home + "/Documents"))
        XCTAssertTrue(policy.isProtected("/Library/LaunchDaemons/x"))
        XCTAssertTrue(policy.isProtected("/private/etc/x"))

        var testing = policy!
        testing.exemptContainerSuffixes = [".xctrunner"]
        XCTAssertFalse(testing.isProtected(home + "/Library/Containers/com.x.UITests.xctrunner/Data/tmp/a"))
        XCTAssertTrue(testing.isProtected(home + "/Library/Containers/com.x/Data/tmp/a"))

        XCTAssertTrue(URLCommandPolicy.isCleanAbsolutePath("/a/b/"))
        XCTAssertFalse(URLCommandPolicy.isCleanAbsolutePath("a/b"))
        XCTAssertFalse(URLCommandPolicy.isCleanAbsolutePath("/a/../b"))
        XCTAssertFalse(URLCommandPolicy.isCleanAbsolutePath("/a/./b"))
        XCTAssertFalse(URLCommandPolicy.isCleanAbsolutePath("/a//b"))
        XCTAssertFalse(URLCommandPolicy.isCleanAbsolutePath("/a/b\n/c"))
    }

    func testDanglingLinkTargetIsRefused() throws {
        try FileManager.default.createSymbolicLink(atPath: downloads + "/two", withDestinationPath: root + "/nowhere/deeper")
        let sel = selection(["two.zip"])
        let command = FinderMenuModel.command(verb: "SevenZipExtractTo", selection: sel)!
        assertRefused(command.argv(for: sel.paths).argv, "where a dangling link would write is unknown")
    }
}
